### ISSUE TITLE
Upstreaming cl-async-process and building the binaries

### ISSUE THREAD

**Issue by jgarte** [logoraz/lem-guix-package-recipe#1]
Hi,

I got the C sources to build for cl-async-process:

https://issues.guix.gnu.org/73170

The `sbcl-async-process` package in this channel does not actually build the C sources.

I'm planning to continue upstreaming parts of lem. 

Would you be interested in sending patches upstream for me to review of other dependencies that are ready?

**Comment by logoraz** [comment]
Hey Jgarte,

Was just looking at revising my recipe, however, it appears no more work is needed - someone beat me to the punch and submitted a package recipe upstream for lem in Guix!
